name: RPGPlugin
version: '${project.version}'
main: com.example.rpgplugin.RPGPlugin
api-version: '1.20'
author: YourName
description: A Minecraft RPG plugin

commands:
  rpg:
    description: Main RPG command
    usage: /rpg <subcommand>
    aliases: [rp]

permissions:
  rpg.use:
    description: Allows using RPG commands
    default: true
