name: MCRPG
version: '${project.version}'
main: com.example.rpgplugin.RPGPlugin
api-version: '1.20'
author: RPGPlugin Team
description: A Minecraft RPG plugin with stats, classes, and skills

# オプション依存（あれば機能拡張）
softdepend:
  - PlaceholderAPI
  - Skript

# プラグインが読み込まれる前にロードする必要があるプラグイン
loadbefore: []

commands:
  rpg:
    description: Main RPG command
    usage: /rpg <subcommand>
    aliases: [rp]

  rpgapi:
    description: RPG API command for external scripts
    usage: /rpgapi <action> <args...>
    aliases: [rpg api]
    permission: rpgplugin.api

  rpgadmin:
    description: Admin RPG command for reloading
    usage: /rpgadmin <subcommand>
    aliases: [rpga, rpgadm]
    permission: rpgplugin.admin

permissions:
  rpg.use:
    description: Allows using RPG commands
    default: true
  rpg.admin:
    description: Allows administrative RPG commands
    default: op
    children:
      rpg.use: true
  rpgplugin.api:
    description: Allows using RPG API commands (for Skript/Denizen integration)
    default: false
