name: MCRPG
version: '${project.version}'
main: com.example.rpgplugin.RPGPlugin
api-version: '1.20'
author: YourName
description: A Minecraft RPG plugin

# 依存プラグイン
depend:
  - Vault
  - MythicMobs

# オプション依存（あれば機能拡張）
softdepend:
  - PlaceholderAPI

# プラグインが読み込まれる前にロードする必要があるプラグイン
loadbefore: []

commands:
  rpg:
    description: Main RPG command
    usage: /rpg <subcommand>
    aliases: [rp]

permissions:
  rpg.use:
    description: Allows using RPG commands
    default: true
  rpg.admin:
    description: Allows administrative RPG commands
    default: op
    children:
      rpg.use: true
  rpgplugin.api:
    description: Allows using RPG API commands (for Skript/Denizen integration)
    default: false

